host = "0.0.0.0"
port = 51780
env = "prod"
astro_port = 5342
prod_astro_build = true
cors_url = "astrox.spaceout.pl"
cookie_domain = "astrox.spaceout.pl"  # Uncomment for production to enable subdomain cookie sharing

[public_keys]
public_api_url = "https://astrox.spaceout.pl/api"
