host = "localhost"
port = 8080
env = "dev"
astro_port = 5431
prod_astro_build = true
cors_url = "localhost"
# cookie_domain = ".spaceout.pl"  # Uncomment for production to enable subdomain cookie sharing

[public_keys]
public_api_url = "http://localhost:8080/api"
